export const FETCH_PROFILE_LIST_START = "FETCH_PROFILE_LIST_START";
export const FETCH_PROFILE_LIST_SUCESS = "FETCH_PROFILE_LIST_SUCESS";
export const FETCH_PROFILE_LIST_FAILURE = "FETCH_PROFILE_LIST_FAILURE";
export const SET_SINGLE_PROFILE_LIST = "SET_SINGLE_PROFILE_LIST";
